### ISSUE TITLE
use multiple separator.

### ISSUE THREAD

**Issue by rhoit** [milkypostman/powerline#109]
Is it possible to use more than one separator, like zig-zag and wave at same time.

**Comment by jasonm23** [comment]
Not without extending the separator logic

**Comment by rhoit** [comment]
is there possibility force render at the time of calling, or something like argument to the separator specifying the type.

**Comment by milkypostman** [comment]
you mean force a re-render? because of the memoization? no but maybe that
could be added if you wanted to but I'm not sure how you would decide. you
can always reset the cache.

as far as multiple separators, this can easily be achieved by writing your
own theme which uses the separator functions directly instead of using the
function assigned to the 'current separator' variable.

**Comment by rhoit** [comment]
@milkypostman  I would like to use function assigned with 'current separator' variable, but I'm not expert on elisp, can you point me to right direction, so I can update my own theme.

**Comment by milkypostman** [comment]
if you look in powerline-separators you'll see a bunch of lines, `(defmacro
pl/<name> ...`. So if it says, `pl/rounded` then there is a function
`pl/rounded-left` and `pl/rounded-right` that are defined. You can use
those. functions.

**Comment by rhoit** [comment]
@milkypostman i tried using those function but its not working.

![screenshot48](https://cloud.githubusercontent.com/assets/1684754/12006491/9f59219c-ac01-11e5-9452-d69247424b46.png)

**Comment by milkypostman** [comment]
sorry, i forgot how I implemented this; unfortunately I did something very clever here which I have learned is a terrible coding idea.

anyways, I tried your config and except for for some octoicon error, i was able to just insert `(powerline-contour-right face2 face1)` and that worked in your modeline.

**Comment by milkypostman** [comment]
you shouldn't call pl/make-xpm or anything, the functions are already defined at https://github.com/milkypostman/powerline/blob/master/powerline.el#L180

again, it's my bad I did this so clever, I would never write it like this again :(

**Comment by jasonm23** [comment]
:+1: for non-clever code

**Comment by milkypostman** [comment]
It's working but you are passing the same face for both sides. Change it to
(powerline-arrow-right face1 face2)

**Comment by rhoit** [comment]
yeah! thanx! :tada:, my dump code! working :laughing: 
:heavy_plus_sign: i dunno how :octocat: works, i just copy/pasted and remixed it.

![screenshot52](https://cloud.githubusercontent.com/assets/1684754/12008763/056a699e-ac7c-11e5-8e84-44531d02083b.png)

**Comment by jasonm23** [comment]
:+1:

**Comment by milkypostman** [comment]
cool looks styling!

**Comment by rhoit** [comment]
@milkypostman thanx, finally I can sleep in peace.

![modline02](https://cloud.githubusercontent.com/assets/1684754/12009438/d6c025fc-ac9e-11e5-9044-ac175a848d41.png)

**Comment by jasonm23** [comment]
Post your patch on reddit/r/Emacs :)
