### ISSUE TITLE
Bottom → Bot

### ISSUE THREAD

**Issue by rhoit** [milkypostman/powerline#110]
Would that be possible to write "Bot" instead of "Bottom" when at the end of buffer?

**Comment by milkypostman** [comment]
i think the idea is to make it so that it's the same width as "Top". If you
want to make it changeable via custom variable I'd be happy to entertain
the pull request.

**Comment by rhoit** [comment]
I look at the http://www.gnu.org/software/emacs/manual/html_node/elisp/_0025_002dConstructs.html
it seem the default behaviour will truncate to first three letters. I'm not able to find where to change the variable, @milkypostman do you have any idea, where in powerline it was changed.

**Comment by rhoit** [comment]
finally solved it using predefined stuff.

```
(setq column-number-mode nil)
(setq line-number-mode nil)
(powerline-raw mode-line-position face1)
```
