### ISSUE TITLE
Separators disappearing on ALT+TAB

### ISSUE THREAD

**Issue by manuel-uberti** [milkypostman/powerline#120]
I think it's easier to explain this issue with some pictures:

![2016-05-05-171533_1919x63_scrot](https://cloud.githubusercontent.com/assets/8199224/15047395/10d67b4a-12e5-11e6-9aad-a7a604e70de9.png)

This happens with all the separators:

![2016-05-05-171707_1919x65_scrot](https://cloud.githubusercontent.com/assets/8199224/15047414/2142f846-12e5-11e6-896e-937c9b1463e1.png)

It also happens with a different theme:

![2016-05-05-171850_1919x79_scrot](https://cloud.githubusercontent.com/assets/8199224/15047446/4d08a624-12e5-11e6-9a56-51189ee62718.png)

And with `emacs -Q` as well:

![2016-05-05-172008_1919x60_scrot](https://cloud.githubusercontent.com/assets/8199224/15047490/802f0480-12e5-11e6-8d73-7cb495778161.png)

I am using latest `powerline` from MELPA, on GNU Emacs 25.0.93.1 (x86_64-debian-linux-gnu, GTK+ Version 3.14.5) of 2016-05-05. 

All I do is switching between windows with ALT+TAB, and upon returning on the Emacs windows this is what I see.

**Comment by manuel-uberti** [comment]
Don't know if it could be of any help, but everything works fine with this fork by @abo-abo: https://github.com/abo-abo/powerline

**Comment by manuel-uberti** [comment]
Nothing here? :)

**Comment by abo-abo** [comment]
@manuel-uberti 
See `counsel-load-theme-action`, it calls `powerline-reset` to change the mode line fringe colors.

And may I say that I really like the theme you're using:)

**Comment by manuel-uberti** [comment]
You don't say ;)

Anyways, with latest Powerline from MELPA the issue is still present.

**Comment by manuel-uberti** [comment]
ping :)

**Comment by milkypostman** [comment]
i'm confused about what the resolution is here? @abo-abo should we integrate your changes?

**Comment by abo-abo** [comment]
@milkypostman Wouldn't hurt I guess, they're fairly innocuous.

But since the changes are a year old, I think the current problem is due to the presence of the new changes in the mainline, rather than the absence of my changes.

Try to `git bisect` the problem across the commits made in the past year.

**Comment by manuel-uberti** [comment]
anything? :)

**Comment by manuel-uberti** [comment]
ping  :)

**Comment by milkypostman** [comment]
sorry to be silent but I don't have time to debug the issue. I would suggest that someone from the community try to figure out what is wrong. I'm happy to accept PRs.

**Comment by manuel-uberti** [comment]
I tried merging @abo-abo repo with latest commits on this main repo, but still nothing. Hard to understand what goes wrong, sorry. :(

**Comment by stiell** [comment]
Looks like this bug was introduced in 3b0f50887db7b484bf9f9d76d1287ea6f3f53a8d.

As I understand it, that commit makes powerline treat the window as inactive upon receiving a WM focus-out event, while Emacs' own mode line handling apparently does not. This results in a mismatch between the separator which expects `mode-line-inactive` and the neighbouring part which uses the `mode-line` face.

**Comment by manuel-uberti** [comment]
Still ugly with Solarized light.
![powerline](https://cloud.githubusercontent.com/assets/8199224/18032861/23df0e26-6d14-11e6-978c-ec318113f70b.png)

**Comment by manuel-uberti** [comment]
There seem to be no solution for this. Should I close this issue and forget about it? :)

**Comment by abo-abo** [comment]
@manuel-uberti Try `(remove-hook 'focus-out-hook 'powerline-unset-selected-window)`.

**Comment by manuel-uberti** [comment]
@abo-abo same problem
