### ISSUE TITLE
Split window behavior

### ISSUE THREAD

**Issue by eflanigan00** [milkypostman/powerline#137]
When I split window I lose the line/column number and percent of the file information because I have a lot of modes active. When I split I don't care as much about the minor modes.
I would like to have the modes be on the far right of the screen with the other information to the left.
That display is more consistent with the original Emacs line:
buffer name | line/column number | modes
Is there a way to move the line/column number and percent to the left?

**Comment by milkypostman** [comment]
i'd recommend coming up with your own theme using the provided powerline
widgets. if you feel it should be included in the package feel free to send
a PR.
