### ISSUE TITLE
After `powerline` update, `mode-icons` not visible until `C-c C-r` (e.g. under `web-mode`)

### ISSUE THREAD

**Issue by dennismayr** [milkypostman/powerline#147]
Hi,

today, package `powerline` was updated.
After `powerline` update, `mode-icons` not visible until `C-c C-r` (e.g. under `web-mode`)

Take a look at the bottom, on the right side of the filename:
![PHP file just loaded, no icon.](https://i.imgur.com/egJzLsu.png)
(PHP file just loaded, no icon.)

![After manually reloading with C-c C-r](https://i.imgur.com/OM4S8qD.png)
(After manually reloading with C-c C-r)

Not sure if it's a `powerline` or `mode-icons` issue.

**Comment by dennismayr** [comment]
Well, I'll be damned: the issue seems to have disappeared after closing a file and reopening it.

**Comment by dennismayr** [comment]
Update: the glitch randomly reappeared.

**Comment by milkypostman** [comment]
huh, i can't imagine what this is. only possibility is #141 i would guess but I don't see how. I merged #146 too but don't see how that could be causing this.  going to submit #130 and maybe that will fix it. did you recently upgrade Emacsen?

**Comment by dennismayr** [comment]
Hi!

No, I'm using the stable Emacs 25 package from ppa:kelleyk/emacs, no further updates lately, or correlated to the issue. It all started, however, after updating the powerline package.

**Comment by milkypostman** [comment]
could you see if #115 fixes this by patching into a local version?
