### ISSUE TITLE
Buffer names containing % are interpreted as escape codes

### ISSUE THREAD

**Issue by m-plamann** [milkypostman/powerline#152]
If I have powerline enabled and visit a file named "foo%bar", the buffer name displays as "foofoofoo%bararar" in the mode line.

It seems like % characters in buffer names are being interpreted as escape codes twice.

**Comment by kmartin** [comment]
I am seeing a similar problem with minor mode lighter. If I add a `%` character to the lighter, it just cuts of the remaining portion of the string.

**Comment by sr105-tm** [comment]
I have the same issue with bitbake recipe filenames which use % as a wildcard character.

**Comment by milkypostman** [comment]
Would you mind sending a PR?

**Comment by sr105-tm** [comment]
Not at all. I'm trying to find a minimal fix for it, but I'm new to elisp. The repeated calls to `format-mode-line` make it difficult. The code assumes that calling `format-mode-line` repeatedly is safe which is not true.

**Comment by skangas** [comment]
The fix is simple, I think. You could just replace any % in the buffer name with %%.

**Comment by milkypostman** [comment]
@skangas do you think #192 makes sense though? it's been a long time since I was in the code, but it does seem to be double parsing?
