### ISSUE TITLE
Rendering issues with window-system

### ISSUE THREAD

**Issue by alexandru** [milkypostman/powerline#175]
Not sure what I'm doing wrong — rendering works perfectly within the terminal (using [iTerm2](https://iterm2.com/)) which has built-in support for powerline glyphs:

![image](https://user-images.githubusercontent.com/11753/74835227-8f391680-5325-11ea-94b1-884033ad9f90.png)

However using the GUI, on MacOS, those characters aren't rendered correctly:

![image](https://user-images.githubusercontent.com/11753/74835326-b98ad400-5325-11ea-9af4-727192f69be3.png)

I did install the [patched fonts](https://github.com/powerline/fonts). Initialization is standard:

```lisp
(use-package powerline
  :ensure t
  :config
  (powerline-default-theme))
```

Anything I'm doing wrong?

I'm using Emacs 26.3 installed via `brew cask install emacs` (I think this is the [emacsformacosx.com/](https://emacsformacosx.com/) build).

**Comment by c-alpha** [comment]
Regarding the rendering of the separators, have you tried setting
```lisp
(setq powerline-image-apple-rgb t)
```
as suggested in https://github.com/milkypostman/powerline/issues/99#issuecomment-410567206? Did that trick for me.

Notwithstanding any other rendering hiccups you might be perceiving though...

**Comment by alexandru** [comment]
@c-alpha thanks, the suggestions in that thread seem to be fixing the background issue.

I still get missing symbols, e.g. these are missing from the GUI version:

![image](https://user-images.githubusercontent.com/11753/74841069-b77a4280-5330-11ea-8eb7-be646a118b8e.png)

![image](https://user-images.githubusercontent.com/11753/74841085-bd702380-5330-11ea-9830-0ae67dc6ed8f.png)

**Comment by c-alpha** [comment]
Have you set this?
```lisp
(setq powerline-gui-use-vcs-glyph 't)
```

**Comment by alexandru** [comment]
@c-alpha ah, that works for the git icon, thank.

**Comment by alexandru** [comment]
Current setup is this:

```lisp
(use-package powerline
  :ensure t
  :init
  (setq ns-use-srgb-colorspace nil)
  (setq powerline-image-apple-rgb 't) ;; doesn't seem to be defined, but leaving it here
  (setq powerline-gui-use-vcs-glyph 't)
  :config
  (powerline-default-theme))
```

Setup is now good enough, will close the issue.
