### ISSUE TITLE
Powerline + large font height with emacs 27.0.91 results in very large height of mode line

### ISSUE THREAD

**Issue by precise-simulation** [milkypostman/powerline#176]
There must be some change in emacs 27 that breaks and significantly increases powerline mode lines height if the font height is set to a large value. (I am testing on emacs build 27.0.91 on a Windows 10 system.) Minimal init.el to reproduce below:

    (custom-set-faces
     '(default ((t (:family "Arial"
                            :foundry "none"
                            :slant normal
                            :weight normal
                            :height 180
                            :width normal)))))

    (add-to-list 'load-path "~/.emacs.d/elpa/powerline-2.4")
    (require 'powerline)
    ;; (setq powerline-height (round (/ (frame-char-height) 3)))
    (powerline-default-theme)

The current workaround I'm using is to set powerline to a third or frame-char-height, but doesn't seem link a good fix (the issue is not present in <=26, and frame-char-height does return the same wether on emacs 26 or 27).

![Clipboard01](https://user-images.githubusercontent.com/18078865/83988870-c54ee480-a96e-11ea-8082-f0ac1286384d.jpg)

Edit: It seems to be some form of HiDpi scaling issue, as without scaling it is not present.

**Comment by tgiannak** [comment]
I can reproduce this on Emacs 27.1 (`GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22) of 2020-08-11`). The problem does not occur if I remove `powerline-hud` from my powerline theme and does occur with a theme consisting only of `powerline-hud`.
