### ISSUE TITLE
separator doesn't render correctly in emacs 28

### ISSUE THREAD

**Issue by jaaasonSun** [milkypostman/powerline#179]
HI,
Not sure if it's a powerline issue or an emacs issue, but separator doesn't render correctly in emacs 28.
I'm current using [emacs-head](https://github.com/daviderestivo/homebrew-emacs-head), and this is the relevant section from `init.el`:
```
(use-package powerline
  :init
  (setq powerline-default-separator 'slant)
  (setq powerline-gui-use-vcs-glyph 't)
  (setq powerline-height 17)
  (setq powerline-image-apple-rgb 't)
  :config (powerline-default-theme))
```

This config works fine in emacs 27.1
<img width="865" alt="截屏2020-10-13 11 40 18" src="https://user-images.githubusercontent.com/6558643/95815874-3ef94380-0d50-11eb-85d2-0ed0ee38b105.png">
This is how it looks in emacs 28.0.50
<img width="865" alt="截屏2020-10-13 11 40 20" src="https://user-images.githubusercontent.com/6558643/95815875-41f43400-0d50-11eb-9780-582a0fabb9fe.png">

Any help is appreciated!

**Comment by milkypostman** [comment]
Have you tried setting `powerline-image-apple-rgb` to `nil`? I'm not putting time into this package anymore so it would have to be someone else putting some time in to debugging and fixing this.

**Comment by jaaasonSun** [comment]
It works!
