### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by jcs090218** [milkypostman/powerline#186]
I am seeing these warnings while installing.

```
powerline-separators.el:34:8:Warning: reference to free variable
    ‘ns-use-srgb-colorspace’

powerline.el:294:8:Warning: function pl/percent-xpm used to take 0+ arguments,
    now takes 8
```

**Comment by milkypostman** [comment]
this project is looking for a maintainer. I'm mostly just approving reasonable pull requests. just to set your expectations.

**Comment by jcs090218** [comment]
Oh, nooo. I have used the package since 2015. :(

I can help maintain this package if you like. It would be great if anyone in Emacs community can help! ❤️

**Comment by milkypostman** [comment]
yes, for now I am still watching over with patches if they make sense. but on a limited basis as justified.

**Comment by skangas** [comment]
For what it's worth, I don't see these warnings here.

**Comment by jcs090218** [comment]
> this project is looking for a maintainer. I'm mostly just approving reasonable pull requests. just to set your expectations.

@milkypostman Are you still looking for maintainer? If yes, I volunteer to become a maintainer. :)

> For what it's worth, I don't see these warnings here.

You are right. It's gone now!
