### ISSUE TITLE
Is customization of inactive powerline separator foreground color possible?

### ISSUE THREAD

**Issue by gamecubate** [milkypostman/powerline#193]
Is there a way (when making some adjustments to a theme via the 'set-face-attribute func) to specify the foreground color of one of the powerline utf-8 separators inside an inactive powerline?

**Comment by milkypostman** [comment]
Which theme are you using?

i don’t think by default you can. But you could add it.  If you look at the theme it should be obvious.

**Comment by gamecubate** [comment]
powerline-default-theme

**Comment by gamecubate** [comment]
I wasn't sure quite how to do it and ended up setting it to a slant for now. 

```
(custom-set-variables
 '(powerline-default-separator "slant"))
```
