### ISSUE TITLE
powerline is not saved properly under Emacs 24.4

### ISSUE THREAD

**Issue by arranger1044** [milkypostman/powerline#58]
With the new `desktop-save-mode` in Emacs 24.4 the powerline is not rendered properly (it gets one color and no messages on it) after the desktop is restored since what Emacs saves in the `.desktop` file is this property in the assoc list:
     (powerline-cache . "Unprintable entity")

Any idea on how to solve this of circumvent this issue?

**Comment by TimePower** [comment]
@seagle0128 
yes, appears again;-(
emacs version 24.3

**Comment by seagle0128** [comment]
Appears again on Emacs 24.4, Mac OSX 10.10.

Error during redisplay: (eval (let* ((active (powerline-selected-window-active)) (mode-line (if active (quote mode-line) (quote mode-line-inactive))) (face1 (if active (quote powerline-active1) (quote powerline-inactive1))) (face2 (if active (quote powerline-active2) (quote powerline-inactive2))) (separator-left (intern (format "powerline-%s-%s" powerline-default-separator (car powerline-default-separator-dir)))) (separator-right (intern (format "powerline-%s-%s" powerline-default-separator (cdr powerline-default-separator-dir)))) (lhs (list (powerline-raw "%*" nil (quote l)) (powerline-buffer-size nil (quote l)) (powerline-buffer-id nil (quote l)) (powerline-raw " ") (funcall separator-left mode-line face1) (powerline-narrow face1 (quote l)) (powerline-vc face1))) (rhs (list (powerline-raw global-mode-string face1 (quote r)) (powerline-raw "%4l" face1 (quote r)) (powerline-raw ":" face1) (powerline-raw "%3c" face1 (quote r)) (funcall separator-right face1 mode-line) (powerline-raw " ") (powerline-raw "%6p" nil (quote r)) (powerline-hud face2 face1))) (center (list (powerline-raw " " face1) (funcall separator-left face1 face2) (when (boundp (quote erc-modified-channels-object)) (p

**Comment by EDmitry** [comment]
My solution doesn't work for the first time you reopen an emacs, but it should work after that. I can't test it now unfortunately because I have stopped using powerline (just makes little sense).
