### ISSUE TITLE
File-error "Cannot open load file" "no such file or directory" "powerline"

### ISSUE THREAD

**Issue by fniessen** [milkypostman/powerline#67]
I installed the powerline package in Emacs 24.3.1.

It works perfectly in that Emacs version, as well in Cygwin Emacs 24.3.1.

However, when launching Emacs 24.3.93.1, I get the (ununderstandable) errors:

Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "powerline")
  (defpowerline powerline-major-mode (propertize (format-mode-line mode-name) (quote mouse-face) (quote mode-line-highlight) (quote help-echo) "Major mode\nmouse-1: Display major mode menu\nmouse-2: Show help for major mode\nmouse-3: Toggle minor modes" (quote local-map) (let ((map (make-sparse-keymap))) (define-key map [mode-line down-mouse-1] (\` (menu-item (\, (purecopy "Menu Bar")) ignore :filter (lambda (_) (mouse-menu-major-mode-map))))) (define-key map [mode-line mouse-2] (quote describe-mode)) (define-key map [mode-line down-mouse-3] mode-line-mode-menu) map)))

See http://screencast.com/t/lCs8lzxBJm4u.

**Comment by jpgtama** [comment]
Tried this? `(add-to-list 'load-path "~/.emacs.d/site-list/rainbow/rainbow-delimiters.el") `

**Comment by jasonm23** [comment]
@jpgtama there is no reference to rainbow-delimiters in the stack trace, and site-list is not a standard location below `.emacs.d`

@fniessen is it possible that you upgraded Powerline recently without restarting Emacs?

**Comment by fniessen** [comment]
This problem is quite old (2014), and I don't suffer of it anymore.
Though, I've not upgraded my packages for some (too long) time right now; but I think this problem can be safely closed -- at least from my side.

I'm doing it.
