### ISSUE TITLE
Background color & arrows

### ISSUE THREAD

**Issue by Silex** [milkypostman/powerline#69]
Hello,

I'm trying to change the background color like in this picture: http://i.imgur.com/lPtIL.png

Here's what I tried:

``` emacs
(set-face-attribute 'mode-line nil
                    :background "OliveDrab3"
                    :box nil)
```

It *almost* works but the arrows don't render properly (they contain grey parts). Any idea?

I know this project is unmaintained so it's fine if you cannot help, can I ask you what do you use now for a "pretty modeline" package?

**Comment by milkypostman** [comment]
@Silex can you try setting the face attribute *before* you load powerline and see if that works?

**Comment by Silex** [comment]
@milkypostman: alright I'll give it a try, thanks.

**Comment by Silex** [comment]
FWIW it works when you do it before loading powerline. Armit Patel's modeline is interesting too!
